/**
 * These types were generated by the tailprops CLI.
 *
 * You can edit them if you want, but they will be overwritten
 * the next time you or someone else run the CLI.
 *
 * If you have updated your Tailwind theme and you want these types
 * to reflect those changes run `npx tailprops typegen <framework>`.
 */
import "preact";

declare module "preact" {
  namespace JSX {
    interface HTMLAttributes {
      tw?: string;
      "tw-hover"?: string;
      "tw-focus"?: string;
      "tw-active"?: string;
      "tw-disabled"?: string;
      "tw-group_hover"?: string;
      "tw-group_focus"?: string;
      "tw-group_active"?: string;
      "tw-group_disabled"?: string;
      "tw-sm"?: string;
      "tw-md"?: string;
      "tw-lg"?: string;
      "tw-xl"?: string;
      "tw-2xl"?: string;
    }
  }
}
